"""Config-driven skeleton generator built on codegen.CodeGen.

Turns a plain-dict config into a Python module skeleton. Demonstrates
conditional blocks, loop-generated blocks, comment/blank-line handling,
and keyword-safe identifiers.

Config schema (all keys optional)::

    {
      "module_doc": "str",
      "imports": ["os", "sys"],
      "constants": {"NAME": "repr-able value"},
      "classes": [
        {"name": "str", "doc": "str", "enabled": True,
         "methods": [{"name": "str", "args": ["self", ...],
                      "doc": "str", "body": ["line", ...],
                      "enabled": True}]}
      ],
      "functions": [ {"name": "str", "args": [...], "body": [...],
                      "enabled": True} ],
    }
"""

from codegen import CodeGen, safe_ident


def generate(config):
    gen = CodeGen()

    gen.comment("Generated by skeleton.py - do not edit by hand.")
    if config.get("module_doc"):
        gen.line("\"\"\"" + config["module_doc"] + "\"\"\"")
    gen.blank()

    gen.for_each(
        config.get("imports", []),
        lambda g, mod: g.line("import " + safe_ident(mod)),
        sort_key=str,
    )
    if config.get("imports"):
        gen.blank()

    constants = config.get("constants", {})
    gen.for_each(
        constants.items(),
        lambda g, kv: g.line(safe_ident(kv[0]) + " = " + repr(kv[1])),
        sort_key=lambda kv: kv[0],
    )
    if constants:
        gen.blank()

    gen.for_each(config.get("classes", []), _emit_class,
                 sort_key=lambda c: c["name"])

    gen.for_each(config.get("functions", []), _emit_function,
                 sort_key=lambda f: f["name"])

    return gen.render()


def _emit_class(gen, cls):
    with gen.when(cls.get("enabled", True),
                  "class " + safe_ident(cls["name"]) + ":"):
        if cls.get("doc"):
            gen.line("\"\"\"" + cls["doc"] + "\"\"\"")
        gen.for_each(cls.get("methods", []), _emit_callable,
                     sort_key=lambda m: m["name"])


def _emit_function(gen, fn):
    _emit_callable(gen, fn)


def _emit_callable(gen, spec):
    name = safe_ident(spec["name"])
    args = ", ".join(safe_ident(a) for a in spec.get("args", []))
    with gen.when(spec.get("enabled", True), "def " + name + "(" + args + "):"):
        if spec.get("doc"):
            gen.line("\"\"\"" + spec["doc"] + "\"\"\"")
        for stmt in spec.get("body", []):
            gen.line(stmt)
